baseURL = "https://new.lustin.org/"
languageCode = "ru-ru"
title = "Al Iczin (c)"
theme = "lustin.ogr"
DefaultContentLanguage = "ru"
publishDir = "docs"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
    [languages.ru]
        languageName     = "RUSSIAN"
        languageCode     = "ru-RU"
        contentDir       = "content/ru"
        weight           = 0
        title            = "Привет GHP TITLE"