name = "Lustin.Ogr"
license = "GPLv3"
licenselink = ""
description = ""
homepage = "https://lustin.org"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Alexey Lustin"
  homepage = "https://github.com/aliczin"
